package com.example.project.help;

import java.util.List;

public class CountryHelper {

    public static final List<String> ALL_COUNTRIES = List.of(
            "Afghanistan",
            "Albanien",
            "Algerien",
            "Amerikanisch-Samoa",
            "Amerikanische Jungferninseln",
            "Amerikanische Überseeinseln",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antarktis",
            "Antigua und Barbuda",
            "Argentinien",
            "Armenien",
            "Aruba",
            "Ascension",
            "Aserbaidschan",
            "Australien",
            "Bahamas",
            "Bahrain",
            "Bangladesch",
            "Barbados",
            "Belarus",
            "Belgien",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivien",
            "Bosnien und Herzegowina",
            "Botsuana",
            "Bouvetinsel",
            "Brasilien",
            "Britische Jungferninseln",
            "Britisches Territorium im Indischen Ozean",
            "Brunei Darussalam",
            "Bulgarien",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Ceuta und Melilla",
            "Chile",
            "China",
            "Clipperton-Insel",
            "Cookinseln",
            "Costa Rica",
            "Curaçao",
            "Côte d’Ivoire",
            "Deutschland",
            "Diego Garcia",
            "Dominica",
            "Dominikanische Republik",
            "Dschibuti",
            "Dänemark",
            "Ecuador",
            "El Salvador",
            "Eritrea",
            "Estland",
            "Eswatini",
            "Europäische Union",
            "Eurozone",
            "Falklandinseln",
            "Fidschi",
            "Finnland",
            "Frankreich",
            "Französisch-Guayana",
            "Französisch-Polynesien",
            "Französische Süd- und Antarktisgebiete",
            "Färöer",
            "Gabun",
            "Gambia",
            "Georgien",
            "Ghana",
            "Gibraltar",
            "Grenada",
            "Griechenland",
            "Grönland",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guernsey",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Heard und McDonaldinseln",
            "Honduras",
            "Indien",
            "Indonesien",
            "Irak",
            "Iran",
            "Irland",
            "Island",
            "Isle of Man",
            "Israel",
            "Italien",
            "Jamaika",
            "Japan",
            "Jemen",
            "Jersey",
            "Jordanien",
            "Kaimaninseln",
            "Kambodscha",
            "Kamerun",
            "Kanada",
            "Kanarische Inseln",
            "Karibische Niederlande",
            "Kasachstan",
            "Katar",
            "Kenia",
            "Kirgisistan",
            "Kiribati",
            "Kokosinseln",
            "Kolumbien",
            "Komoren",
            "Kongo-Brazzaville",
            "Kongo-Kinshasa",
            "Kosovo",
            "Kroatien",
            "Kuba",
            "Kuwait",
            "Laos",
            "Lesotho",
            "Lettland",
            "Libanon",
            "Liberia",
            "Libyen",
            "Liechtenstein",
            "Litauen",
            "Luxemburg",
            "Madagaskar",
            "Malawi",
            "Malaysia",
            "Malediven",
            "Mali",
            "Malta",
            "Marokko",
            "Marshallinseln",
            "Martinique",
            "Mauretanien",
            "Mauritius",
            "Mayotte",
            "Mexiko",
            "Mikronesien",
            "Monaco",
            "Mongolei",
            "Montenegro",
            "Montserrat",
            "Mosambik",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Neukaledonien",
            "Neuseeland",
            "Nicaragua",
            "Niederlande",
            "Niger",
            "Nigeria",
            "Niue",
            "Nordkorea",
            "Nordmazedonien",
            "Norfolkinsel",
            "Norwegen",
            "Nördliche Marianen",
            "Oman",
            "Pakistan",
            "Palau",
            "Palästinensische Autonomiegebiete",
            "Panama",
            "Papua-Neuguinea",
            "Paraguay",
            "Peru",
            "Philippinen",
            "Pitcairninseln",
            "Polen",
            "Portugal",
            "Puerto Rico",
            "Republik Moldau",
            "Ruanda",
            "Rumänien",
            "Russland",
            "Réunion",
            "Salomonen",
            "Sambia",
            "Samoa",
            "San Marino",
            "Saudi-Arabien",
            "Schweden",
            "Schweiz",
            "Senegal",
            "Serbien",
            "Seychellen",
            "Sierra Leone",
            "Simbabwe",
            "Singapur",
            "Sint Maarten",
            "Slowakei",
            "Slowenien",
            "Somalia",
            "Spanien",
            "Spitzbergen und Jan Mayen",
            "Sri Lanka",
            "St. Barthélemy",
            "St. Helena",
            "St. Kitts und Nevis",
            "St. Lucia",
            "St. Martin",
            "St. Pierre und Miquelon",
            "St. Vincent und die Grenadinen",
            "Sudan",
            "Suriname",
            "Syrien",
            "São Tomé und Príncipe",
            "Südafrika",
            "Südgeorgien und die Südlichen Sandwichinseln",
            "Südkorea",
            "Südsudan",
            "Tadschikistan",
            "Taiwan",
            "Tansania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad und Tobago",
            "Tristan da Cunha",
            "Tschad",
            "Tschechien",
            "Tunesien",
            "Turkmenistan",
            "Turks- und Caicosinseln",
            "Tuvalu",
            "Türkei",
            "Uganda",
            "Ukraine",
            "Ungarn",
            "Uruguay",
            "Usbekistan",
            "Vanuatu",
            "Vatikanstadt",
            "Venezuela",
            "Vereinigte Arabische Emirate",
            "Vereinigte Staaten",
            "Vereinigtes Königreich",
            "Vereinte Nationen",
            "Vietnam",
            "Wallis und Futuna",
            "Weihnachtsinsel",
            "Westsahara",
            "Zentralafrikanische Republik",
            "Zypern",
            "Ägypten",
            "Äquatorialguinea",
            "Äthiopien",
            "Äußeres Ozeanien",
            "Ålandinseln",
            "Österreich"
    );

}
